name: pypsa-eur-sec-30-path
channels:
  - anaconda
  - bioconda
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - pip==9.0.1
  - python==3.6.3
  - pip:    
    - appdirs==1.4.3
    - countrycode==0.2
    - pyomo==5.3
    - pypsa==0.13.0
    - pyutilib==5.6
    - tables==3.4.2
    - vresutils==0.2.3
    - xarray==0.10.7
    - snakemake==3.13.3
    - decorator==4.1.2
    - fiona==1.7.10
    - h5py==2.7.0
    - matplotlib==2.1.0  
    - networkx==2.0
    - numpy==1.13.3
    - pandas==0.20.3
    - pillow==4.2.1
    - pyyaml==3.12 
    - scipy==0.19.1
    - seaborn==0.8.0
    - shapely==1.6.2 
    - xlrd==1.1.0 

